const canvas=document.getElementById('canvas');let selected=null;let drag=null;const snap=20;let counts={};
const names={floor:'바닥',wall:'벽',column:'기둥',roof:'지붕',window:'창문',door:'문',stairs:'계단',balcony:'발코니',tree:'나무',bench:'벤치',lamp:'조명',plant:'화분'};
document.querySelectorAll('.tool').forEach(t=>t.addEventListener('dragstart',e=>e.dataTransfer.setData('type',t.dataset.type)));
canvas.addEventListener('dragover',e=>e.preventDefault());
canvas.addEventListener('drop',e=>{e.preventDefault();const type=e.dataTransfer.getData('type');if(type) addPiece(type,e.offsetX,e.offsetY)});
function snapTo(v){return Math.round(v/snap)*snap}
function addPiece(type,x,y){const el=document.createElement('div');el.className='piece '+type;el.dataset.type=type;el.textContent=type==='tree'?'🌳':type==='lamp'?'💡':type==='plant'?'🪴':type==='bench'?'':type==='window'?'':type==='door'?'':type==='floor'?'':type==='wall'?'':type==='column'?'':type==='roof'?'':type==='stairs'?'':type==='balcony'?'':'';el.style.left=Math.max(0,snapTo(x-20))+'px';el.style.top=Math.max(0,snapTo(y-20))+'px';canvas.appendChild(el);bindPiece(el);select(el);update()}
function bindPiece(el){el.addEventListener('pointerdown',e=>{e.preventDefault();select(el);drag={el,ox:e.clientX-el.offsetLeft,oy:e.clientY-el.offsetTop};el.setPointerCapture(e.pointerId)});el.addEventListener('pointermove',e=>{if(!drag||drag.el!==el)return;const r=canvas.getBoundingClientRect();let x=snapTo(e.clientX-r.left-20),y=snapTo(e.clientY-r.top-20);el.style.left=Math.max(0,Math.min(canvas.clientWidth-el.offsetWidth,x))+'px';el.style.top=Math.max(0,Math.min(canvas.clientHeight-el.offsetHeight,y))+'px'});el.addEventListener('pointerup',()=>{drag=null;update()});el.addEventListener('dblclick',()=>{el.remove();selected=null;update()})}
function select(el){document.querySelectorAll('.piece.selected').forEach(x=>x.classList.remove('selected'));selected=el;if(el)el.classList.add('selected')}
document.getElementById('rotate').onclick=()=>{if(selected){selected.style.transform='rotate('+(+(selected.dataset.rot||0)+90)+'deg)';selected.dataset.rot=(+(selected.dataset.rot||0)+90)%360}};
document.getElementById('delete').onclick=()=>{if(selected){selected.remove();selected=null;update()}};
document.addEventListener('keydown',e=>{if(e.key==='Delete')document.getElementById('delete').click()});
function update(){counts={};document.querySelectorAll('.piece').forEach(p=>counts[p.dataset.type]=(counts[p.dataset.type]||0)+1);const checks=[counts.column>=4,counts.wall>=2,counts.floor>=1,counts.column>=1&&counts.wall>=1];let n=checks.filter(Boolean).length;['m1','m2','m3','m4'].forEach((id,i)=>{document.getElementById(id).classList.toggle('ok',checks[i]);document.getElementById(id).textContent=(checks[i]?'✓ ':'○ ')+document.getElementById(id).textContent.replace(/^[✓○] /,'')});document.getElementById('score').textContent=n+' / 4 조건'}
document.getElementById('check').onclick=()=>{const n=+document.getElementById('score').textContent[0];const r=document.getElementById('result');if(n===4){r.textContent='✓ SUCCESS · 내진 미션 통과';r.style.color='#34d399';r.style.borderColor='#10b981'}else{r.textContent='✕ FAIL · '+n+'/4 조건 충족';r.style.color='#fca5a5';r.style.borderColor='#ef4444'}};
[['floor',200,240],['column',240,260],['column',320,260],['column',240,340],['column',320,340],['wall',240,240],['wall',240,380]].forEach(([t,x,y])=>addPiece(t,x,y));
const arModal=document.getElementById('arModal'),arMessage=document.getElementById('arMessage');
document.getElementById('arMode').onclick=()=>{arModal.classList.add('open');arModal.setAttribute('aria-hidden','false');arMessage.textContent='AR 미리보기가 시작되었습니다. 화면 중앙의 모형을 실제 공간에 맞춰보세요.'};
function closeAR(){arModal.classList.remove('open');arModal.setAttribute('aria-hidden','true')}
document.getElementById('closeAr').onclick=closeAR;
document.getElementById('arPlace').onclick=()=>{arMessage.textContent='✓ 설계 모형을 배치했습니다.';document.getElementById('arModel').style.transform='translate(-50%,-20%) perspective(600px) rotateX(8deg) rotateY(-18deg) scale(1.08)'};
