const canvas=document.getElementById("canvas"),svg=document.getElementById("svg3d");
const names={floor:"바닥",wall:"벽",column:"기둥",roof:"지붕",window:"창문",door:"문",stairs:"계단",balcony:"발코니",solar:"태양광",tree:"나무",bench:"벤치",lamp:"조명",plant:"화분",sofa:"소파",table:"테이블",bed:"침대",cabinet:"수납장"},icons={tree:"🌳",lamp:"💡",plant:"🪴",sofa:"▰",table:"▱",bed:"▭",cabinet:"▤"};
const defaults={floor:[600,600],wall:[600,20],column:[24,24],roof:[240,140],window:[120,120],door:[90,210],stairs:[80,45],balcony:[90,25],solar:[80,45],tree:[40,40],bench:[65,20],lamp:[30,30],plant:[35,35],sofa:[85,45],table:[70,45],bed:[95,55],cabinet:[70,50]};
let selected=null,view="2d",snap=2,gridOn=true,zoom=1,history=[],future=[],cam={yaw:-35,pitch:.38,scale:1};
const snapTo=v=>Math.round(v/snap)*snap;
function status(t){const e=document.getElementById("status");e.textContent=t;clearTimeout(window.st);window.st=setTimeout(()=>e.textContent=gridOn?"2cm 스냅 ON":"모눈 OFF",1400)}
function snapshot(){return [...canvas.children].map(p=>({type:p.dataset.type,x:p.offsetLeft,y:p.offsetTop,w:p.offsetWidth,h:p.offsetHeight,r:+p.dataset.r||0}))}
function save(){history.push(snapshot());if(history.length>40)history.shift();future=[]}
function add(type,x,y,o={}){const [dw,dh]=defaults[type]||[60,40],p=document.createElement("div");p.className="piece "+type;p.dataset.type=type;p.dataset.r=o.r||0;p.style.left=snapTo(x)+"px";p.style.top=snapTo(y)+"px";p.style.width=(o.w??dw)+"px";p.style.height=(o.h??dh)+"px";p.style.transform="rotate("+(o.r||0)+"deg)";if(icons[type])p.textContent=icons[type];canvas.appendChild(p);bind(p);return p}
function bind(p){p.addEventListener("pointerdown",e=>{if(view!=="2d")return;e.preventDefault();e.stopPropagation();select(p);p._drag={x:e.clientX,y:e.clientY,l:p.offsetLeft,t:p.offsetTop};p.setPointerCapture(e.pointerId)});p.addEventListener("pointermove",e=>{if(!p._drag)return;const dx=(e.clientX-p._drag.x)/zoom,dy=(e.clientY-p._drag.y)/zoom;p.style.left=Math.max(0,Math.min(900-p.offsetWidth,snapTo(p._drag.l+dx)))+"px";p.style.top=Math.max(0,Math.min(620-p.offsetHeight,snapTo(p._drag.t+dy)))+"px";info(p)});p.addEventListener("pointerup",()=>{if(p._drag){p._drag=null;update();render3d()}});p.addEventListener("click",e=>{e.stopPropagation();select(p)})}
function select(p){document.querySelectorAll(".selected").forEach(x=>x.classList.remove("selected"));selected=p;if(p)p.classList.add("selected");info(p)}
function info(p){const b=document.getElementById("selectedInfo");if(!p){b.textContent="요소를 선택하면 위치와 크기가 표시됩니다.";return}b.innerHTML="<b>"+names[p.dataset.type]+"</b><br>X "+(p.offsetLeft/100).toFixed(2)+"m · Y "+(p.offsetTop/100).toFixed(2)+"m<br>크기 "+(p.offsetWidth/100).toFixed(2)+"m × "+(p.offsetHeight/100).toFixed(2)+"m<br>회전 "+p.dataset.r+"°"}
function update(){const c={};[...canvas.children].forEach(p=>c[p.dataset.type]=(c[p.dataset.type]||0)+1);document.getElementById("count").textContent=canvas.children.length;document.getElementById("columns").textContent=c.column||0;document.getElementById("walls").textContent=c.wall||0;document.getElementById("floors").textContent=c.floor||0;const ok=[(c.column||0)>=4,(c.wall||0)>=4,(c.floor||0)>=1,(c.column||0)>=1&&(c.wall||0)>=1],labels=["기둥 4개 이상","벽 4개 이상","바닥 1개 이상","구조 요소 함께 사용"];ok.forEach((v,i)=>{const e=document.getElementById("m"+(i+1));e.className=v?"ok":"";e.textContent=(v?"✓ ":"○ ")+labels[i]});document.getElementById("score").textContent=ok.filter(Boolean).length+" / 4 조건"}
function addUser(type){save();const [w,h]=defaults[type]||[60,40];add(type,snapTo(450-w/2),snapTo(310-h/2));update();render3d();status(names[type]+" 추가됨")}
function deleteSel(){if(!selected)return;save();selected.remove();selected=null;update();render3d();status("요소 삭제됨")}
function rotate(){if(!selected)return;save();const r=(+selected.dataset.r+90)%360;selected.dataset.r=r;selected.style.transform="rotate("+r+"deg)";info(selected);render3d();status("90° 회전")}
function clearRoom(){canvas.innerHTML="";selected=null}
function defaultRoom(){clearRoom();const x=150,y=10,s=600,t=20;add("floor",x,y,{w:s,h:s});add("wall",x,y,{w:s,h:t});add("wall",x,y+s-t,{w:s,h:t});add("wall",x,y,{w:t,h:s});add("wall",x+s-t,y,{w:t,h:s});add("column",x-2,y-2);add("column",x+s-t-2,y-2);add("column",x-2,y+s-t-2);add("column",x+s-t-2,y+s-t-2);select(null);update();render3d();status("6m × 6m 기본 방 생성")}
function restore(state){clearRoom();state.forEach(o=>add(o.type,o.x,o.y,{w:o.w,h:o.h,r:o.r}));select(null);update();render3d()}
function setView(v){view=v;const three=v==="3d";canvas.style.display=three?"none":"block";document.getElementById("scene3d").classList.toggle("show",three);document.getElementById("view2d").classList.toggle("active",!three);document.getElementById("view3d").classList.toggle("active",three);document.getElementById("legend").textContent=three?"🖱️ 3D 드래그: 시점 회전 · 휠: 확대/축소":"🖱️ 드래그 이동 · ↻ 회전 · DEL 삭제 · 📐 2cm 스냅 · 휠 확대/축소";if(three)render3d();status(three?"3D 보기":"2D 평면도")}
function P(x,y,z=0){const a=cam.yaw*Math.PI/180,c=Math.cos(a),s=Math.sin(a),X=x*c-y*s,Y=x*s+y*c;return [500+(X-Y)*.62*cam.scale,360+(X+Y)*cam.pitch*cam.scale-z*cam.scale]}
function poly(points,cls){const e=document.createElementNS("http://www.w3.org/2000/svg","polygon");e.setAttribute("points",points.map(q=>q.join(",")).join(" "));e.setAttribute("class",cls);svg.appendChild(e)}
function line(a,b,cls){const e=document.createElementNS("http://www.w3.org/2000/svg","line");e.setAttribute("x1",a[0]);e.setAttribute("y1",a[1]);e.setAttribute("x2",b[0]);e.setAttribute("y2",b[1]);e.setAttribute("class",cls);svg.appendChild(e)}
function prism(x,y,w,h,z,r,cls){const a=r*Math.PI/180,c=Math.cos(a),s=Math.sin(a),q=[[0,0],[w,0],[w,h],[0,h]].map(([u,v])=>[x+u*c-v*s,y+u*s+v*c]),B=q.map(v=>P(v[0],v[1],0)),T=q.map(v=>P(v[0],v[1],z));poly([B[0],B[1],T[1],T[0]],cls+"-front");poly([B[1],B[2],T[2],T[1]],cls+"-side");poly([T[0],T[1],T[2],T[3]],cls+"-top")}
function render3d(){svg.innerHTML="";const floor=[...canvas.children].find(p=>p.dataset.type==="floor");if(floor){const x=floor.offsetLeft,y=floor.offsetTop,w=floor.offsetWidth,h=floor.offsetHeight,a=(+floor.dataset.r||0)*Math.PI/180,c=Math.cos(a),s=Math.sin(a),q=[[0,0],[w,0],[w,h],[0,h]].map(([u,v])=>[x+u*c-v*s,y+u*s+v*c]);poly(q.map(v=>P(v[0],v[1],0)),"svg-floor");for(let u=0;u<=w;u+=100)line(P(x+u*c,y+u*s),P(x+u*c-h*s,y+u*s+h*c),"svg-grid");for(let v=0;v<=h;v+=100)line(P(x-v*s,y+v*c),P(x+w*c-v*s,y+w*s+v*c),"svg-grid")}
[...canvas.children].filter(p=>p.dataset.type!=="floor").sort((a,b)=>(a.offsetLeft+a.offsetTop)-(b.offsetLeft+b.offsetTop)).forEach(p=>{const t=p.dataset.type,x=p.offsetLeft,y=p.offsetTop,w=p.offsetWidth,h=p.offsetHeight,r=+p.dataset.r||0;if(t==="wall")prism(x,y,w,h,300,r,"svg-wall");else if(t==="column")prism(x,y,w,h,260,r,"svg-column");else if(t==="roof")prism(x,y,w,h,300,r,"svg-roof");else{const q=[P(x,y,6),P(x+w,y,6),P(x+w,y+h,6),P(x,y+h,6)];poly(q,t==="window"?"svg-window":"svg-object");if(icons[t]){const e=document.createElementNS("http://www.w3.org/2000/svg","text");e.setAttribute("x",(q[0][0]+q[2][0])/2);e.setAttribute("y",(q[0][1]+q[2][1])/2);e.setAttribute("text-anchor","middle");e.setAttribute("font-size","24");e.textContent=icons[t];svg.appendChild(e)}}})}
function camera(m){cam=m==="iso"?{yaw:-35,pitch:.38,scale:1}:m==="top"?{yaw:-35,pitch:.02,scale:.92}:{yaw:10,pitch:.22,scale:1.05};render3d();document.querySelectorAll(".scene-tools button").forEach(b=>b.classList.remove("active"));document.getElementById(m==="iso"?"iso":m==="top"?"top":"walk").classList.add("active")}
document.querySelectorAll(".tool").forEach(b=>b.onclick=()=>addUser(b.dataset.type));document.getElementById("rotate").onclick=rotate;document.getElementById("delete").onclick=deleteSel;document.addEventListener("keydown",e=>{if(e.key==="Delete")deleteSel();if(e.key.toLowerCase()==="r")rotate()});document.getElementById("newBtn").onclick=()=>{if(confirm("현재 설계를 새 6m × 6m 방으로 바꿀까요?")){save();defaultRoom()}};document.getElementById("undoBtn").onclick=()=>{if(history.length){future.push(snapshot());restore(history.pop());status("실행 취소")}};document.getElementById("redoBtn").onclick=()=>{if(future.length){history.push(snapshot());restore(future.pop());status("다시 실행")}};document.getElementById("gridBtn").onclick=()=>{gridOn=!gridOn;canvas.classList.toggle("grid-off",!gridOn);document.getElementById("snapPill").textContent=gridOn?"SNAP 2cm":"SNAP OFF";status(gridOn?"2cm 스냅 ON":"모눈 OFF")};document.getElementById("search").oninput=e=>{const q=e.target.value.trim();document.querySelectorAll(".tool").forEach(b=>b.style.display=!q||b.textContent.includes(q)?"":"none")};canvas.onclick=()=>select(null);
canvas.onwheel=e=>{e.preventDefault();zoom=Math.max(.7,Math.min(1.5,zoom+(e.deltaY<0?.08:-.08)));canvas.style.transform="scale("+zoom+")";};document.getElementById("view2d").onclick=()=>setView("2d");document.getElementById("view3d").onclick=()=>setView("3d");document.getElementById("iso").onclick=()=>camera("iso");document.getElementById("top").onclick=()=>camera("top");document.getElementById("walk").onclick=()=>camera("walk");document.getElementById("resetCam").onclick=()=>camera("iso");
let d3=null;svg.onpointerdown=e=>{d3={x:e.clientX,y:e.clientY};svg.setPointerCapture(e.pointerId)};svg.onpointermove=e=>{if(!d3)return;cam.yaw+=(e.clientX-d3.x)*.35;cam.pitch=Math.max(.08,Math.min(.65,cam.pitch-(e.clientY-d3.y)*.002));d3={x:e.clientX,y:e.clientY};render3d()};svg.onpointerup=()=>d3=null;svg.onpointercancel=()=>d3=null;svg.onwheel=e=>{e.preventDefault();cam.scale=Math.max(.65,Math.min(1.5,cam.scale+(e.deltaY<0?.06:-.06)));render3d()};
document.getElementById("check").onclick=()=>{const c={};[...canvas.children].forEach(p=>c[p.dataset.type]=(c[p.dataset.type]||0)+1);const n=[(c.column||0)>=4,(c.wall||0)>=4,(c.floor||0)>=1,(c.column||0)>=1&&(c.wall||0)>=1].filter(Boolean).length,r=document.getElementById("result");r.textContent=n===4?"✓ SUCCESS · 내진 미션 통과":"✕ FAIL · "+n+"/4 조건 충족";r.style.color=n===4?"#10b981":"#ef4444";status(n===4?"미션 성공!":"조건을 더 충족해 보세요")};
document.getElementById("cameraAr").onclick=async()=>{const m=document.getElementById("arModal"),v=document.getElementById("video");m.classList.add("open");try{v.srcObject=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment"},audio:false});document.getElementById("arMessage").textContent="카메라가 준비됐습니다."}catch(e){document.getElementById("arMessage").textContent="카메라 권한이 없어 AR 미리보기 모드로 실행됩니다."}};document.getElementById("arBtn").onclick=()=>document.getElementById("cameraAr").click();document.getElementById("closeAr").onclick=()=>{const v=document.getElementById("video");if(v.srcObject)v.srcObject.getTracks().forEach(t=>t.stop());document.getElementById("arModal").classList.remove("open")};document.getElementById("placeAr").onclick=()=>status("AR 배치 미리보기 실행");document.getElementById("openUrl").onclick=()=>{const u=document.getElementById("appUrl").value.trim();if(/^https?:\\/\\//i.test(u))window.open(u,"_blank","noopener,noreferrer");else status("https:// 주소를 입력하세요")};
defaultRoom();